### ISSUE TITLE
Query on use case scenario

### ISSUE THREAD

**Issue by Agenetics** [Shuhua-Group/MultiWaveInfer2.0#2]
Hi,

From you paper, as I understand it, only the target needs to be supplied as input and not the reference sources to infer admixture history  in that target. Is that correct?

Considering that I am a novice, how do I go about converting diploid target data in plink/geno format into the ancestry track input required for this program? Does the program work for one sample at a time? How does phasing factor into this? (I note that you have used PhaseIt in your paper to phase the real world data).

Thank you.

**Comment by Zhang-Rui-2018** [comment]
Hi,

Sorry for the late reply!

Yes! Only the target needs to be supplied as input.

You could use local ancestry inference tool (like HAPMIX, RFMix, Loter, and so on) to get the ancestry track. It usually takes all your target samples as input to infer the local ancestry and typically, the input genome should be phased.

Best,
Rui
